#pragma once
enum class GAME_STEP : unsigned int { STEP_LOGIN, STEP_TITLE, STEP_MAKER, STEP_SINGLE_PLAY, STEP_UPLOAD, STEP_DOWNLOAD, STEP_LOBBY, STEP_ROOM, STEP_TEAM };

enum LOGIN : unsigned int { LOGIN_CREATE_ID_BT, LOGIN_GAME_START_BT };
enum LOGIN_TEXT : unsigned int { LOGIN_TEXT_RESULT, LOGIN_TEXT_NICKNAME };

enum TITLE : unsigned int { TITLE_MAKER_BT, TITLE_SINGLE_PLAY_BT, TITLE_MULTIPLAY_BT, TITLE_UPLOAD_MAP_BT, TITLE_DOWNLOAD_MAP_BT };

enum BUTTON_STATE { BUTTON_ON, BUTTON_OFF };

enum PLAYER_TYPE { MARIO, LUIGI, TOAD, TOADETTE };

enum PLAYER_STATE { STATE_SMALL = 0, STATE_BIG = 10, STATE_FIRE = 20 };

enum DIRECTION { FRONT = 0, LEFT = 0, RIGHT = 1 };

enum PLAYER_ACT { ACT_SIT = 0, ACT_IDLE = 2, ACT_RUN = 4, ACT_STOP = 6, ACT_JUMP = 8, ACT_ATTECT = 10, ACT_DIE = 32 };

// SOUND
enum SOUDN_BGM : unsigned int { TITLE_BGM }; // 

enum SOUND_EFFRCT : unsigned int { SOUND_BUTTON }; // 